<?php

/**
 * @file
 * Provides advanced recurring billing for licenses.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function commerce_license_billing_ctools_plugin_directory($module, $plugin) {
  if ($module == 'commerce_license_billing') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_ctools_plugin_type().
 */
function commerce_license_billing_ctools_plugin_type() {
  $plugins['billing_cycle_engine'] = array(
    'classes' => array('class'),
  );

  return $plugins;
}

/**
 * Returns the available billing cycle engine plugins.
 */
function commerce_license_billing_cycle_engine_plugins() {
  ctools_include('plugins');
  $plugins = ctools_get_plugins('commerce_license_billing', 'billing_cycle_engine');
  foreach ($plugins as $key => $plugin) {
    if (!class_exists($plugin['class'])) {
      // Invalid class specified.
      unset($plugins[$key]);
      continue;
    }
  }
  uasort($plugins, 'ctools_plugin_sort');
  return $plugins;
}

/**
 * Implements hook_entity_info().
 */
function commerce_license_billing_entity_info() {
  // commerce_license_billing_cycle_type is too long for Drupal, so all
  // entity types and field names had to have their prefix shortened to cl_.
  // Yuck.
  $entity_info['cl_billing_cycle'] = array(
    'label' => t('Commerce License Billing Cycle'),
    'module' => 'commerce_license_billing',
    'base table' => 'cl_billing_cycle',
    'entity class' => 'CommerceLicenseBillingCycle',
    'controller class' => 'EntityAPIController',
    'label callback' => 'entity_class_label',
    'fieldable' => FALSE,
    'bundles' => array(),
    'bundle keys' => array(
      'bundle' => 'name',
    ),
    'entity keys' => array(
      'id' => 'billing_cycle_id',
      'bundle' => 'type',
    ),
  );
  // Bypass entity_load() as it cannot be used here (recursion).
  $billing_cycle_type = db_select('cl_billing_cycle_type', 'bct')
    ->fields('bct', array('name', 'title'))
    ->execute()
    ->fetchAllKeyed();
  foreach ($billing_cycle_type as $name => $title) {
    $entity_info['cl_billing_cycle']['bundles'][$name] = array(
      'label' => $title,
    );
  }

  $entity_info['cl_billing_cycle_type'] = array(
    'label' => t('Commerce License Billing Cycle Type'),
    'module' => 'commerce_license_billing',
    'base table' => 'cl_billing_cycle_type',
    'access callback' => 'commerce_license_billing_cycle_type_access',
    'controller class' => 'EntityBundlePluginEntityControllerExportable',
    'fieldable' => TRUE,
    'exportable' => TRUE,
    'bundles' => array(),
    'bundle of' => 'cl_billing_cycle',
    'bundle plugin' => array(
      'plugin type' => 'billing_cycle_engine',
    ),
    'entity keys' => array(
      'id' => 'billing_cycle_type_id',
      'bundle' => 'engine',
      'label' => 'title',
      'name' => 'name',
    ),
    'admin ui' => array(
      'path' => 'admin/commerce/config/license/billing-cycle-types',
      'file' => 'includes/commerce_license_billing.cycle_type_ui.inc',
      'controller class' => 'CommerceLicenseBillingCycleTypeUIController',
    ),
  );
  // Bypass entity_load() as it cannot be used here (recursion).
  foreach (commerce_license_billing_cycle_engine_plugins() as $name => $plugin) {
    $entity_info['cl_billing_cycle_type']['bundles'][$name] = array(
      'label' => $plugin['title'],
    );
  }

  return $entity_info;
}

/**
 * Implements hook_entity_info_alter().
 */
function commerce_license_billing_entity_info_alter(&$entity_info) {
  $entity_info['commerce_order']['bundles']['recurring'] = array(
    'label' => t('Recurring'),
  );
}

/**
 * Implements hook_commerce_line_item_type_info().
 */
function commerce_license_billing_commerce_line_item_type_info() {
  $line_item_types = array();
  $line_item_types['recurring'] = array(
    'type' => 'recurring',
    'name' => t('Recurring'),
    'description' => t('References a product in a recurring order.'),
    'product' => TRUE,
    'add_form_submit_value' => t('Add product'),
    'base' => 'commerce_product_line_item',
  );

  return $line_item_types;
}

/**
 * Access callback for the entity API.
 *
 * @param $op
 *   The operation being performed. One of 'view', 'update', 'create', 'delete'
 *   or just 'edit' (being the same as 'create' or 'update').
 * @param $cycle_type
 *   (optional) A cycle type to check access for. If nothing is given, access
 *   for all cycle types is determined.
 * @param $account
 *   (optional) The user to check for. Leave it to NULL to check for the global
 *   user.
 *
 * @return boolean
 *   Whether access is allowed or not.
 */
function commerce_license_billing_cycle_type_access($op, $cycle_type = NULL, $account = NULL) {
  $engines = commerce_license_billing_cycle_engine_plugins();
  return user_access('administer licenses', $account) && !empty($engines);
}

/**
 * Implements hook_commerce_order_state_info().
 */
function commerce_license_billing_commerce_order_state_info() {
  $order_states['recurring'] = array(
    'name' => 'recurring',
    'title' => t('Recurring order'),
    'description' => t('Orders in this state are used for recurring payments.'),
    'weight' => 10,
    'default_status' => 'recurring_open',
  );
  return $order_states;
}

/**
 * Implements hook_commerce_order_status_info().
 */
function commerce_license_billing_commerce_order_status_info() {
  $order_statuses = array();
  $order_statuses['recurring_open'] = array(
    'name' => 'recurring_open',
    'title' => t('Recurring open'),
    'state' => 'recurring',
  );
  $order_statuses['recurring_pending'] = array(
    'name' => 'recurring_pending',
    'title' => t('Recurring pending'),
    'state' => 'recurring',
  );
  $order_statuses['recurring_complete'] = array(
    'name' => 'recurring_complete',
    'title' => t('Recurring complete'),
    'state' => 'recurring',
  );
  return $order_statuses;
}

/**
 * Implements hook_flush_caches().
 */
function commerce_license_billing_flush_caches() {
  commerce_license_billing_configure_product_types();
  commerce_license_billing_configure_line_item_type();
  commerce_license_billing_configure_order_type();
}

/**
 * Implements hook_cron().
 */
function commerce_license_billing_cron() {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'cl_billing_cycle')
    ->propertyCondition('status', 1)
    ->propertyCondition('end', REQUEST_TIME, '<=');
  $results = $query->execute();
  if (!empty($results['cl_billing_cycle'])) {
    $billing_cycle_ids = array_keys($results['cl_billing_cycle']);
    foreach (array_keys($results['cl_billing_cycle']) as $billing_cycle_id) {
      $queue = DrupalQueue::get('commerce_license_billing_cycle_expiration');
      $task = array(
        'billing_cycle_id' => $billing_cycle_id,
        'title' => 'Billing cycle #' . $billing_cycle_id,
      );
      $queue->createItem($task);
    }
  }
}

/**
 * Implements hook_advanced_queue_info().
 */
function commerce_license_billing_advanced_queue_info() {
  return array(
    'commerce_license_billing_cycle_expiration' => array(
      'worker callback' => 'commerce_license_billing_cycle_expiration_queue_process',
    ),
  );
}

/**
 * Worker callback for expiring billing cycles.
 */
function commerce_license_billing_cycle_expiration_queue_process($item) {
  $billing_cycle_id = $item->data['billing_cycle_id'];
  $billing_cycle = entity_load_single('cl_billing_cycle', $billing_cycle_id);

  // Load the order for this billing cycle.
  $query = new EntityFieldQuery;
  $query
    ->entityCondition('entity_type', 'commerce_order')
    ->propertyCondition('status', array('recurring_open'))
    ->fieldCondition('cl_billing_cycle', 'target_id', $billing_cycle_id);
  $result = $query->execute();
  if (!$result) {
    // No order found (which should never happen), so nothing else to be done.
    return;
  }
  $order_id = key($result['commerce_order']);
  $order = commerce_order_load($order_id);

  // Gather licenses.
  $licenses = commerce_license_billing_get_recurring_order_licenses($order);
  $can_close = TRUE;
  foreach ($licenses as $license) {
    if ($license instanceof CommerceLicenseBillingUsageInterface) {
      // Do gap checking to ensure usage has been reported for the entire cycle.
      $usage = commerce_license_billing_usage_list($license);
      $remaining_gap = ($billing_cycle->end - $billing_cycle->start);
      foreach ($usage as $usage_entry) {
        if ($usage_entry['start'] <= $billing_cycle->start) {
          $usage_entry['start'] = $billing_cycle->start;
        }
        if (!$usage_entry['end']) {
          $usage_entry['end'] = $billing_cycle->end;
        }
        $remaining_gap -= ($usage_entry['end'] - $usage_entry['start']);
      }

      if ($remaining_gap > 0) {
        $can_close = FALSE;
      }
    }
  }

  if ($can_close) {
    // Close the billing cycle.
    $billing_cycle->start = 0;
    $billing_cycle->save();
    // Close the order.
    $order->status = 'recurring_complete';
    commerce_order_save($order);
    // Clean up usage that's now irrelevant.
    foreach ($licenses as $license) {
      commerce_license_billing_usage_clear($license);
    }

    // Open a new billing cycle just after the end of the previous one.
    $billing_cycle_type = entity_load_single('cl_billing_cycle_type', $billing_cycle->type);
    $next_billing_cycle = $billing_cycle_type->getNextBillingCycle($billing_cycle);
    // Create a new recurring order.
    commerce_license_billing_create_recurring_order($order, $next_billing_cycle, $licenses);

    return array(
      'status' => ADVANCEDQUEUE_STATUS_SUCCESS,
      'result' => 'Closed the billing cycle.',
    );
  }
  else {
    if ($order->status != 'recurring_pending') {
      $order->status = 'recurring_pending';
      commerce_order_save($order);
    }

    return array(
      'status' => ADVANCEDQUEUE_STATUS_FAILURE,
      'result' => 'Incomplete usage information.',
    );
  }
}

/**
 * Returns all licenses found on a recurring order.
 *
 * @param $order
 *   The order entity.
 *
 * @return
 *   An array of all found licenses, keyed by license id.
 */
function commerce_license_billing_get_recurring_order_licenses($order) {
  $licenses = array();
  $wrapper = entity_metadata_wrapper('commerce_order', $order);
  foreach ($wrapper->commerce_line_items as $line_item_wrapper) {
    if (isset($line_item_wrapper->cl_billing_license)) {
      $license_id = $line_item_wrapper->cl_billing_license->raw();
      if (!isset($licenses[$license_id])) {
        $licenses[$license_id] = $line_item_wrapper->cl_billing_license->value();
      }
    }
  }

  return $licenses;
}

/**
 * Creates recurring orders for products in the provided order.
 *
 * The provided order is first scanned, and all licensable products are
 * gathered. Their billing cycle types are gathered, and the appropriate
 * billing cyles are opened (if they haven't been previously).
 * An order per billing cycle is created (if it hasn't been previously),
 * and the new line items are added.
 *
 * @param $order
 *   The order to use as a base of the new recurring order.
 */
function commerce_license_billing_create_recurring_orders($order) {
  // Group licenses by billing cycle type.
  $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
  $billing_cycle_type_ids = array();
  $grouped_licenses = array();
  foreach ($order_wrapper->commerce_line_items as $line_item_wrapper) {
    if (!empty($line_item_wrapper->value()->commerce_license)) {
      $product_wrapper = $line_item_wrapper->commerce_product;
      if (!empty($product_wrapper->value()->cl_billing_cycle_type)) {
        $billing_cycle_type_id = $product_wrapper->cl_billing_cycle_type->raw();
        $billing_cycle_type_ids[] = $billing_cycle_type_id;
        $grouped_licenses[$billing_cycle_type_id][] = $line_item_wrapper->commerce_license->value();
      }
    }
  }
  // Load all found billing cycle types.
  $billing_cycle_types = entity_load('cl_billing_cycle_type', $billing_cycle_type_ids);

  // Ensure there's a recurring order for each group of licenses.
  foreach ($grouped_licenses as $billing_cycle_type_id => $licenses) {
    $billing_cycle_type = $billing_cycle_types[$billing_cycle_type_id];
    $billing_cycle = $billing_cycle_type->getBillingCycle($order->uid);

    // Open the product history.
    foreach ($licenses as $license) {
      commerce_license_billing_product_history_open($license, $license->product_id);
    }

    // Check if there's an existing order attached to that billing cycle.
    $query = new EntityFieldQuery();
    $query
      ->entityCondition('entity_type', 'commerce_order')
      ->entityCondition('bundle', 'recurring')
      ->propertyCondition('status', 'recurring_open')
      ->propertyCondition('uid', $order->uid)
      ->fieldCondition('cl_billing_cycle', 'target_id', $billing_cycle->billing_cycle_id);
    $results = $query->execute();
    if (!empty($results['commerce_order'])) {
      $recurring_order_id = key($results['commerce_order']);
      $recurring_order = commerce_order_load($recurring_order_id);
      $recurring_order_wrapper = entity_metadata_wrapper('commerce_order', $recurring_order);
      // Generate a base line item for each license.
      $existing_line_items = $recurring_order_wrapper->commerce_line_items->value();
      $line_items = array();
      foreach ($licenses as $license) {
        $line_items[] = commerce_license_billing_generate_base_line_item($license, $billing_cycle, $recurring_order_id);
      }
      $recurring_order_wrapper->commerce_line_items = array_merge($existing_line_items, $line_items);
      $recurring_order_wrapper->save();
    }
    else {
      commerce_license_billing_create_recurring_order($order, $billing_cycle, $licenses);
    }
  }
}

/**
 * Creates and saves a new recurring order.
 *
 * @param $previous_order
 *   The previous order.
 * @param $billing_cycle
 *   The billing cycle for the new order.
 * @param $licenses
 *   An array of licenses added to the new order.
 *
 * @return
 *   A saved recurring order.
 */
function commerce_license_billing_create_recurring_order($previous_order, $billing_cycle, $licenses) {
  $previous_order_wrapper = entity_metadata_wrapper('commerce_order', $previous_order);
  // Create a new order and save it immediately to get the order_id.
  $recurring_order = commerce_order_new($previous_order->uid, 'recurring_open', 'recurring');
  commerce_order_save($recurring_order);

  $recurring_order_wrapper = entity_metadata_wrapper('commerce_order', $recurring_order);
  $recurring_order_wrapper->commerce_customer_billing = $previous_order_wrapper->commerce_customer_billing->value();
  $recurring_order_wrapper->cl_billing_cycle = $billing_cycle;
  // Generate a base line item for each license.
  // If this is the first recurring order, licenses of all statuses are taken,
  // since they haven't been activated yet. However, if the previous order was
  // also recurring, only active licenses are taken since the revoked / expired
  // ones have already been charged for.
  $active_only = ($previous_order->type == 'recurring');
  $line_items = array();
  foreach ($licenses as $license) {
    if (!$active_only && $license->status != COMMERCE_LICENSE_ACTIVE) {
      continue;
    }
    $line_items[] = commerce_license_billing_generate_base_line_item($license, $billing_cycle, $recurring_order->order_id);
  }
  $recurring_order_wrapper->commerce_line_items = $line_items;
  $recurring_order_wrapper->save();

  return $recurring_order;
}

/**
 * Generates the recurring line item for the base product of a license.
 *
 * Takes into account whether the product is prepaid or postpaid.
 *
 * @param $license
 *   The license entity.
 * @param $billing_cycle
 *   The billing cycle entity.
 * @param $order_id
 *   The order_id to be set on the newly created line items.
 *
 * @return
 *   The newly created and saved line item.
 */
function commerce_license_billing_generate_base_line_item($license, $billing_cycle, $order_id) {
  $product_wrapper = $license->wrapper->product;
  // Charge for the base product, there's no usage at this point.
  $line_item = commerce_line_item_new('recurring', $order_id);
  $line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $line_item);
  $line_item_wrapper->line_item_label = $product_wrapper->title->value();
  $line_item_wrapper->commerce_product = $product_wrapper->value();
  $line_item_wrapper->quantity = 1;
  $line_item_wrapper->cl_billing_license = $license;

  $line_item_wrapper->commerce_unit_price = $license->wrapper->product->commerce_price->value();
  if ($product_wrapper->cl_billing_type->value() == 'prepaid') {
    // In case of prepaid, the line item always charges for the next
    // billing cycle. So if the just opened billing cycle is "February",
    // the line item needs to charge for March.
    $billing_cycle_type = entity_load_single('cl_billing_cycle_type', $billing_cycle->type);
    $next_billing_cycle = $billing_cycle_type->getNextBillingCycle($billing_cycle, FALSE);
    $line_item_wrapper->cl_billing_start = $billing_cycle->start;
    $line_item_wrapper->cl_billing_end = $billing_cycle->end;
  }
  elseif ($product_wrapper->cl_billing_type->value() == 'postpaid') {
    // In case of postpaid, the line item always charges for the current
    // billing cycle.
    $line_item_wrapper->cl_billing_start = $billing_cycle->start;
    $line_item_wrapper->cl_billing_end = $billing_cycle->end;
  }
  // Trigger price calculation to get any needed discounts or price changes.
  rules_invoke_event('commerce_product_calculate_sell_price', $line_item);
  // Save the line item.
  $line_item_wrapper->save();

  return $line_item_wrapper->value();
}

/**
 * Implements hook_commerce_order_load().
 *
 * When a recurring order gets loaded, update its line items based on latest
 * product history and usage. This is a process similar to the cart refresh
 * done by commerce_cart_commerce_order_load().
 */
function commerce_license_billing_commerce_order_load($orders) {
  $refreshed = &drupal_static(__FUNCTION__, array());
  $recurring_statuses = array('recurring_open', 'recurring_pending');

  foreach ($orders as $order) {
    // Refresh only if this is a recurring order and it hasn't been refreshed.
    if (!isset($refreshed[$order->order_id]) && in_array($order->status, $recurring_statuses)) {
      // Refresh the order and add its ID to the refreshed array.
      $refreshed[$order->order_id] = TRUE;
      commerce_license_billing_order_refresh($order);
    }
  }
}

/**
 * Updates the recurring order based on latest product history and usage.
 *
 * @param $order
 *   The order entity.
 */
function commerce_license_billing_order_refresh($order) {
  // The first time an order is saved, entity_load_unchanged() in the controller
  // leads to this function being called, with no line items to work on.
  if (empty($order->commerce_line_items)) {
    return;
  }

  $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
  $billing_cycle = $order_wrapper->cl_billing_cycle->value();
  $licenses = array();
  $old_line_items = array();
  $line_items = array();
  foreach ($order_wrapper->commerce_line_items as $delta => $line_item_wrapper) {
    // Gather all licenses that are in this order.
    $license_id = $line_item_wrapper->cl_billing_license->raw();
    if (!isset($licenses[$license_id])) {
      $licenses[$license_id] = $line_item_wrapper->cl_billing_license->value();
    }

    // Group the old line items by their license id.
    $old_line_items[$license_id][] = $line_item_wrapper;
  }

  $order_changed = FALSE;
  foreach ($licenses as $license_id => $license) {
    $charges = commerce_license_billing_collect_charges($license, $billing_cycle);
    foreach ($charges as $charge) {
      $line_item = NULL;
      // Try to find an existing line item that can be updated.
      foreach ($old_line_items[$license_id] as $line_item_wrapper) {
        // Assume we found a match, then unset it if any of the properties
        // used for comparison ($charge['match']) don't match.
        $line_item = $line_item_wrapper->value();
        foreach ($charge['match'] as $key) {
          if ($line_item_wrapper->{$key}->value() != $charge[$key]) {
            $line_item = NULL;
          }
        }
      }

      // No line item found, create one.
      if (!$line_item) {
        $line_item = commerce_line_item_new('recurring', $order->order_id);
        $line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $line_item);
        $line_item_wrapper->line_item_label = $charge['commerce_product']->title;
        $line_item_wrapper->commerce_product = $charge['commerce_product'];
        $line_item_wrapper->quantity = $charge['quantity'];
        $line_item_wrapper->cl_billing_license = $license;
        $order_changed = TRUE;
      }

      $line_item_wrapper->commerce_unit_price = $charge['commerce_unit_price'];
      $line_item_wrapper->cl_billing_start = $charge['cl_billing_start'];
      $line_item_wrapper->cl_billing_end = $charge['cl_billing_end'];
      // Trigger price calculation to get any needed discounts or price changes.
      rules_invoke_event('commerce_product_calculate_sell_price', $line_item);
      // Save the line item.
      $line_item_wrapper->save();
      $line_items[] = $line_item_wrapper->value();
    }
  }

  // Update the order, if new line items were created.
  if ($order_changed) {
    $order_wrapper->commerce_line_items = $line_items;
    $order_wrapper->save();
  }
}

/**
 * Collects charges for a license in the given billing cycle.
 *
 * @param $license
 *   The license entity.
 * @param $billing_cycle
 *   The billing cycle entity.
 *
 * @return
 *   An array of charge arrays that have the following keys:
 *   - quantity: The quantity of the charge.
 *   - commerce_product: The product entity that represents the charge.
 *   - commerce_unit_price: The unit price of the charge.
 *   - cl_billing_start: The start of the period covered by the charge.
 *   - cl_billing_end: The end of the period covered by the charge.
 *   - match: An array of keys to compare on the charge and the line item
 *     when looking for an existing line item for the charge.
 */
function commerce_license_billing_collect_charges($license, $billing_cycle) {
  $history = commerce_license_billing_product_history_list($license);
  // Gather all products.
  foreach ($history as $history_entry) {
    $product_ids[] = $history_entry['product_id'];
  }
  $products = commerce_product_load_multiple($product_ids);
  $charges = array();

  // Charge for the plans (current one, and any previous ones).
  foreach ($history as $history_entry) {
    $product = $products[$history_entry['product_id']];
    $product_wrapper = entity_metadata_wrapper('commerce_product', $product);

    $charges[] = array(
      'quantity' => 1,
      'commerce_product' => $product,
      'commerce_unit_price' => $product_wrapper->commerce_price->value(),
      'cl_billing_start' => $history_entry['start'],
      'cl_billing_end' => $history_entry['end'],
      'match' => array('commerce_product'),
      'prorate' => TRUE,
    );
  }

  // Charge for usage, if the license type supports it.
  if ($license instanceof CommerceLicenseBillingUsageInterface) {
    foreach ($license->usageGroups() as $group_name => $group_info) {
      $product = commerce_product_load_by_sku($group_info['product']);
      $product_wrapper = entity_metadata_wrapper('commerce_product', $product);

      if ($group_info['type'] == 'counter') {
        // Counter usage is charged in total for the entire billing cycle,
        // so calculate the total and substract the free quantity from it.
        $current_usage = commerce_license_billing_current_usage($license, $group_name);
        $current_usage -= $group_info['free_quantity'];
        if ($current_usage >= 1) {
          $charges[] = array(
            'commerce_product' => $product,
            'quantity' => $current_usage,
            'commerce_unit_price' => $product_wrapper->commerce_price->value(),
            'cl_billing_start' => $billing_cycle->start,
            'cl_billing_end' => $billing_cycle->end,
            'match' => array('commerce_product'),
          );
        }
      }
      else {
        // Charge for each reported gauge usage. Ignore any usage that is free.
        $usage_list = commerce_license_billing_usage_list($license, $group_name);
        foreach ($usage_list as $usage_entry) {
          if ($usage_entry['quantity'] != $group_info['free_quantity']) {
            $charges[] = array(
              'commerce_product' => $product,
              'quantity' => $usage_entry['quantity'],
              'commerce_unit_price' => $product_wrapper->commerce_price->value(),
              'cl_billing_start' => $usage_entry['start'],
              'cl_billing_end' => $usage_entry['end'],
              'match' => array('commerce_product', 'cl_billing_start', 'cl_billing_end'),
              'prorate' => TRUE,
            );
          }
        }
      }
    }
  }

  // Adjust the collected charges (start, end, price prorating).
  commerce_license_billing_adjust_charges($charges, $billing_cycle);

  return $charges;
}

/**
 * Adjusts the collected charges for the given billing cycle.
 *
 * If the start timestamp is from before the billing cycle was opened
 * (due to plans or usage carried over from previous cycles), the
 * billing cycle's start timestamp is taken instead.
 * If the end timestamp is missing (because it's charging an open-ended plan or
 * gauge usage), the billing cycle's end timestamp is taken instead.
 *
 * After the timestamps have been adjusted, the amounts are prorated if needed,
 * and any charges with prorated amounts smaller than 0.01 are dropped.
 *
 * @param $charges
 *   The charges array provided by commerce_license_billing_collect_charges().
 * @param $billing_cycle
 *   The billing cycle entity.
 */
function commerce_license_billing_adjust_charges(&$charges, $billing_cycle) {
  $billing_cycle_duration = $billing_cycle->end - $billing_cycle->start;
  foreach ($charges as $key => &$charge) {
    // Adjust the start and end timestamps for correct charge estimation.
    if ($charge['cl_billing_start'] < $billing_cycle->start) {
      $charge['cl_billing_start'] = $billing_cycle->start;
    }
    if (empty($charge['cl_billing_end'])) {
      $charge['cl_billing_end'] = $billing_cycle->end;
    }

    // Prorate any charges that require it.
    if (!empty($charge['prorate'])) {
      $price = &$charge['commerce_unit_price'];
      if ($price['amount'] > 0) {
        $duration = $charge['cl_billing_end'] - $charge['cl_billing_start'];
        $price['amount'] = $price['amount'] * ($duration / $billing_cycle_duration);
        $price['amount'] = round($price['amount']);
        // Remove the charge, it is too small.
        if ($price['amount'] < 1) {
          unset($charges[$key]);
        }
      }

      unset($charge['prorate']);
    }
  }
}

/**
 * Estimate the cost of a license with the given plan and usage.
 *
 * @param $license_type
 *   The license type.
 * @param $product
 *   The product representing the license plan.
 * @param $usage
 *  An array in the usage_group => quantity format.
 *
 * @return
 *   An array with the following keys:
 *   - billing_cycle: An array with the title, start, end keys.
 *   - charges: An array of arrays with product, unit_price, quantity keys.
 *   - total: The total price array (amount, currency_code, data).
 */
function commerce_license_billing_estimate_cost($license_type, $product, $usage = NULL) {
  // Prepare commonly needed data.
  $product_wrapper = entity_metadata_wrapper('commerce_product', $product);
  $zero_price = array(
    'amount' => 0,
    'currency_code' => $product_wrapper->commerce_price->currency_code->value(),
    'data' => array(),
  );
  // Construct a billing cycle.
  $billing_cycle_type = $product_wrapper->cl_billing_cycle_type->value();
  $billing_cycle = $billing_cycle_type->getBillingCycle($GLOBALS['user']->uid, REQUEST_TIME, FALSE);

  $estimation = array(
    'billing_cycle' => array(
      'title' => $billing_cycle->label(),
      'start' => $billing_cycle->start,
      'end' => $billing_cycle->end,
    ),
  );
  // Price the base product.
  $estimation['charges'][] = array(
    'product' => $product,
    'quantity' => 1,
    'unit_price' => $product_wrapper->commerce_price->value(),
  );
  // Price the usage.
  $license = entity_create('commerce_license', array('type' => $license_type));
  $license->product_id = $product->product_id;
  $license->granted = $billing_cycle->start;
  $license->expires = $billing_cycle->end;
  if ($license instanceof CommerceLicenseBillingUsageInterface) {
    $usage_groups = $license->usageGroups();
    foreach ($usage as $group_name => $quantity) {
      $usage_group = $usage_groups[$group_name];
      $usage_product = commerce_product_load_by_sku($usage_group['product']);
      $usage_product_wrapper = entity_metadata_wrapper('commerce_product', $usage_product);
      if ($quantity <= $usage_group['free_quantity']) {
        $price = $zero_price;
      }
      else {
        $quantity -= $usage_group['free_quantity'];
        $price = $usage_product_wrapper->commerce_price->value();
      }

      $estimation['charges'][] = array(
        'product' => $usage_product,
        'quantity' => $quantity,
        'unit_price' => $usage_product_wrapper->commerce_price->value(),
      );
    }
  }
  // Calculate the total.
  $estimation['total'] = $zero_price;
  foreach ($estimation['charges'] as $charge) {
    $estimation['total']['amount'] += ($charge['unit_price']['amount'] * $charge['quantity']);
    $estimation['total']['data'] = commerce_price_components_combine($estimation['total'], $charge['unit_price']);
  }
  // Make sure the final amount has been rounded.
  $estimation['total']['amount'] = round($estimation['total']['amount']);

  return $estimation;
}

/**
 * Implements hook_commerce_license_update().
 *
 * Maintains the license product history.
 */
function commerce_license_billing_commerce_license_update($license) {
  $product = $license->wrapper->product->value();
  // No billing cycle type selected, this license is not billable.
  if (empty($product->cl_billing_cycle_type)) {
    return;
  }

  $status_changed = ($license->status > $license->original->status);
  $product_changed = ($license->product_id != $license->original->product_id);
  if ($license->status == COMMERCE_LICENSE_REVOKED && $status_changed) {
    // The license was just revoked.
    commerce_license_billing_product_history_close($license, $license->product_id);
  }
  elseif ($license->status == COMMERCE_LICENSE_ACTIVE && $product_changed) {
    // The license product has changed.
    commerce_license_billing_product_history_close($license, $license->original->product_id);
    commerce_license_billing_product_history_open($license, $license->product_id);
  }
}

/**
 * Creates an open license product history entry.
 *
 * @param $license
 *   The license entity.
 * @param $product_id
 *   The product id.
 */
function commerce_license_billing_product_history_open($license, $product_id) {
  db_insert('cl_product_history')
    ->fields(array(
      'license_id' => $license->license_id,
      'product_id' => $product_id,
      'start' => REQUEST_TIME,
    ))
    ->execute();
}

/**
 * Closes a license product history entry.
 *
 * @param $license
 *   The license entity.
 * @param $product_id
 *   The product id.
 */
function commerce_license_billing_product_history_close($license, $product_id) {
  db_update('cl_product_history')
    ->fields(array(
      'end' => REQUEST_TIME,
    ))
    ->condition('license_id', $license->license_id)
    ->condition('product_id', $product_id)
    ->condition('end', 0)
    ->execute();
}

/**
 * Returns all license product history entries.
 *
 * @param $license
 *   The license entity.
 *
 * @return
 *   An array of history entries.
 */
function commerce_license_billing_product_history_list($license) {
  $data = array(
    ':license_id' => $license->license_id,
  );
  $history = db_query("SELECT * FROM {cl_product_history} WHERE license_id = :license_id", $data)->fetchAll(PDO::FETCH_ASSOC);
  return $history;
}

/**
 * Adds usage for the specified license and usage group.
 *
 * @param $license
 *   The license entity.
 * @param $group
 *   The usage group, as defined by $license->usageGroups().
 * @param $quantity
 *   The usage quantity.
 * @param $start
 *   The unix timestamp when usage started. Optional if the usage group
 *   specified "immediate" => TRUE, otherwise required.
 * @param $end
 *   The unix timestamp when usage ended. Optional if the usage group
 *   specified "immediate" => TRUE, otherwise required.
 */
function commerce_license_billing_usage_add($license, $group, $quantity, $start = NULL, $end = NULL) {
  $usage_groups = $license->usageGroups();
  if (!isset($usage_groups[$group])) {
    throw new Exception('Invalid usage group specified for commerce_license_billing_usage_add().');
  }
  $usage_group = $usage_groups[$group];
  if (empty($usage_group['immediate']) && (!$start || !$end)) {
    throw new Exception('Empty $start or $end timestamps in commerce_license_billing_usage_add().');
  }
  // If usage reporting for this group is immediate, it is safe to initialize
  // $start to current time.
  if (!empty($usage_group['immediate']) && !$start) {
    $start = REQUEST_TIME;
  }

  db_insert('cl_billing_usage')
    ->fields(array(
      'license_id' => $license->license_id,
      'usage_group' => $group,
      'quantity' => $quantity,
      'start' => $start,
      'end' => (int) $end,
    ))
    ->execute();
}

/**
 * Clears usage for the provided license and usage group.
 *
 * @param  $license
 *   The license entity.
 * @param $group
 *   (Optional) The usage group, as defined by $license->usageGroups().
 */
function commerce_license_billing_usage_clear($license, $group = NULL) {
  $delete = db_delete('cl_billing_usage');
  $delete->condition('license_id', $license->license_id);
  $delete->condition('end', 0, '!=');
  if ($group) {
    $delete->condition('usage_group', $group);
  }
  $delete->execute();
}

/**
 * Returns the current usage for the provided license and usage group.
 *
 * If the usage group is of type 'counter', the total usage is returned.
 * If the usage group is of type 'gauge', the last reported usage is returned.
 *
 * @param  $license
 *   The license entity.
 * @param $group
 *   The usage group, as defined by $license->usageGroups().
 *
 * @return
 *   The numeric usage amount.
 */
function commerce_license_billing_current_usage($license, $group) {
  $usage_groups = $license->usageGroups();
  if (!isset($usage_groups[$group])) {
    throw new Exception('Invalid usage group specified for commerce_license_billing_current_usage().');
  }
  $usage_group = $usage_groups[$group];

  $data = array(
    ':license_id' => $license->license_id,
    ':group' => $group,
  );
  if ($usage_group['type'] == 'counter') {
    $usage = db_query("SELECT SUM(quantity) FROM {cl_billing_usage}
                    WHERE license_id = :license_id AND usage_group = :group
                      GROUP BY license_id, usage_group", $data)->fetchColumn();
  }
  elseif ($usage_group['type'] == 'gauge') {
    $usage = db_query("SELECT quantity FROM {cl_billing_usage}
                    WHERE license_id = :license_id AND usage_group = :group
                      ORDER BY start DESC LIMIT 1", $data)->fetchColumn();
  }

  return (int) $usage;
}

/**
 * Returns all usage for the provided license and usage group.
 *
 * @param  $license
 *   The license entity.
 * @param $group
 *   The usage group, as defined by $license->usageGroups().
 *
 * @return
 *   An array of usage records.
 */
function commerce_license_billing_usage_list($license, $group = NULL) {
  $usage_groups = $license->usageGroups();
  if ($group && !isset($usage_groups[$group])) {
    throw new Exception('Invalid usage group specified for commerce_license_billing_usage_list().');
  }

  $query = db_select('cl_billing_usage', 'bu');
  $query
    ->fields('bu')
    ->condition('license_id', $license->license_id);
  if ($group) {
    $query->condition('usage_group', $group);
  }
  return $query->execute()->fetchAll(PDO::FETCH_ASSOC);
}

/**
 * Ensures that the license product types have the required billing fields.
 *
 * Fields:
 * - cl_billing_cycle_type: an entityreference field pointing to the
 *   billing cycle type.
 * - cl_billing_type: an options field for selecting prepaid or postpaid.
 */
function commerce_license_billing_configure_product_types() {
  $field = field_info_field('cl_billing_cycle_type');
  if (empty($field)) {
    $field = array(
      'field_name' => 'cl_billing_cycle_type',
      'type' => 'entityreference',
      'cardinality' => 1,
      'translatable' => 0,
      'module' => 'entityreference',
      'settings' => array(
        'target_type' => 'cl_billing_cycle_type',
        'handler' => 'base',
      ),
    );
    field_create_field($field);
  }
  foreach (commerce_license_product_types() as $type_name) {
    $instance = field_info_instance('commerce_product', 'cl_billing_cycle_type', $type_name);
    if (empty($instance)) {
      $license_type_instance = field_info_instance('commerce_product', 'commerce_license_type', $type_name);
      $instance = array(
        'field_name' => 'cl_billing_cycle_type',
        'entity_type' => 'commerce_product',
        'bundle' => $type_name,
        'label' => 'License billing cycle type',
        'required' => FALSE,
        'widget' => array(
          'type' => 'options_select',
          'module' => 'options',
          // Make sure that this field is shown right after the license type.
          'weight' => $license_type_instance['widget']['weight'] + 1,
        ),
      );
      field_create_instance($instance);
    }
  }

  $field = field_info_field('cl_billing_type');
  if (empty($field)) {
    $field = array(
      'field_name' => 'cl_billing_type',
      'type' => 'list_text',
      'entity_type' => 'commerce_product',
      'cardinality' => 1,
      'translatable' => 0,
      'module' => 'list',
      'settings' => array(
        'allowed_values' => array(
          'prepaid' => 'Prepaid',
          'postpaid' => 'Postpaid'
        ),
      ),
    );
    field_create_field($field);
  }
  foreach (commerce_license_product_types() as $type_name) {
    $instance = field_info_instance('commerce_product', 'cl_billing_type', $type_name);
    if (empty($instance)) {
      $license_type_instance = field_info_instance('commerce_product', 'commerce_license_type', $type_name);
      $instance = array(
        'field_name' => 'cl_billing_type',
        'entity_type' => 'commerce_product',
        'bundle' => $type_name,
        'label' => 'License billing type',
        'required' => TRUE,
        'widget' => array(
          'type' => 'options_buttons',
          'module' => 'options',
          // Make sure that this field is shown right after the billing cycle type.
          'weight' => $license_type_instance['widget']['weight'] + 1,
        ),
      );
      field_create_instance($instance);
    }
  }
}

/**
 * Ensures that the recurring line item type has the required fields.
 *
 * Fields:
 * - cl_billing_start: a datetime field.
 * - cl_billing_end: a datetime field.
 * - cl_billing_license: an entityreference field pointing to the license
 *   for which the line item was generated.
 */
function commerce_license_billing_configure_line_item_type() {
  if (!$line_item_type = commerce_line_item_type_load('recurring')) {
    return;
  }
  // Make sure Commerce has created all of its required fields.
  commerce_line_item_configure_line_item_type($line_item_type);

  $field = field_info_field('cl_billing_start');
  if (empty($field)) {
    $field = array(
      'field_name' => 'cl_billing_start',
      'type' => 'datetime',
      'cardinality' => 1,
      'translatable' => 0,
      'module' => 'date',
    );
    field_create_field($field);
  }
  $instance = field_info_instance('commerce_line_item', 'cl_billing_start', 'recurring');
  if (empty($instance)) {
    $instance = array(
      'field_name' => 'cl_billing_start',
      'entity_type' => 'commerce_line_item',
      'bundle' => 'recurring',
      'label' => 'Billing cycle start',
      'required' => TRUE,
      'widget' => array(
        'type' => 'date_select',
        'module' => 'date',
      ),
    );
    field_create_instance($instance);
  }

  $field = field_info_field('cl_billing_end');
  if (empty($field)) {
    $field = array(
      'field_name' => 'cl_billing_end',
      'type' => 'datetime',
      'cardinality' => 1,
      'translatable' => 0,
      'module' => 'date',
    );
    field_create_field($field);
  }
  $instance = field_info_instance('commerce_line_item', 'cl_billing_end', 'recurring');
  if (empty($instance)) {
    $instance = array(
      'field_name' => 'cl_billing_end',
      'entity_type' => 'commerce_line_item',
      'bundle' => 'recurring',
      'label' => 'Billing cycle end',
      'required' => TRUE,
      'widget' => array(
        'type' => 'date_select',
        'module' => 'date',
      ),
    );
    field_create_instance($instance);
  }

  $field = field_info_field('cl_billing_license');
  if (!$field) {
    $field = array(
      'settings' => array(
        'handler' => 'base',
        'target_type' => 'commerce_license',
      ),
      'field_name' => 'cl_billing_license',
      'type' => 'entityreference',
    );
    field_create_field($field);
  }
  $instance = field_info_instance('commerce_line_item', 'cl_billing_license', 'recurring');
  if (empty($instance)) {
    $instance = array(
      'field_name' => 'cl_billing_license',
      'entity_type' => 'commerce_line_item',
      'bundle' => 'recurring',
      'label' => 'License',
      'required' => TRUE,
    );

    field_create_instance($instance);
  }
}

/**
 * Ensures that the recurring order type has the required fields.
 *
 * Fields:
 * - cl_billing_cycle: an entityreference field pointing to a
 *   billing cycle.
 */
function commerce_license_billing_configure_order_type() {
  // Make sure Commerce has created all of its required fields.
  commerce_order_configure_order_type('recurring');

  $field = field_info_field('cl_billing_cycle');
  if (empty($field)) {
    $field = array(
      'field_name' => 'cl_billing_cycle',
      'type' => 'entityreference',
      'cardinality' => 1,
      'translatable' => 0,
      'module' => 'entityreference',
      'settings' => array(
        'target_type' => 'cl_billing_cycle',
        'handler' => 'base',
      ),
    );
    field_create_field($field);
  }
  $instance = field_info_instance('commerce_order', 'cl_billing_cycle', 'recurring');
  if (empty($instance)) {
    $instance = array(
      'field_name' => 'cl_billing_cycle',
      'entity_type' => 'commerce_order',
      'bundle' => 'recurring',
      'label' => 'Billing cycle',
      'required' => TRUE,
      'widget' => array(
        'type' => 'options_select',
        'module' => 'options',
      ),
    );
    field_create_instance($instance);
  }
}
