<?php

/**
 * Implements hook_ctools_plugin_directory().
 */
function commerce_usage_test_ctools_plugin_directory($module, $plugin) {
  if ($module == 'commerce_usage') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_commerce_product_type_info().
 */
function commerce_usage_test_commerce_product_type_info() {
  $product_types['usage_test'] = array(
    'type' => 'usage_test',
    'name' => 'Usage test',
    'description' => '',
    'help' => '',
    'revision' => FALSE,
    'usage' => array(
      'enabled' => TRUE,
      'plugin' => array(
        'class' => 'CommerceUsageProductUsage_Test',
        'usage callback' => '',
        'estimate callback' => '',
        'is still active callback' => '',
      ),
    ),
  );
  return $product_types;
}
